# The title is the title of your Add-On
title: Hello World
# The description will be shown above the form when activating the Add-On
description: This Add-On downloads files from a MuckRock request and uploads them to a project on DocumentCloud. 
# Optional instructions field to describe how to use the Add-On
instructions: Provide a request ID for the request you would like to retrieve from and a project ID for the project you would like to upload to. 
# Top level type should always be object
type: object
properties:
  # the key is the name of the variable that will be returned to your code
  request_id:
    # the title is what will be shown as the form label
    title: Request ID
    # a string is text
    type: integer
  project_name:
    title: Project name
    description: Project name for the newly created DocumentCloud projects where documents will be uploaded
    type: string
# Categories are what type of Add-On this is. Used to sort the Add-On in the Add-On menu. 
categories: 
  - export
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
version: 2
